from selenium import webdriver
from selenium.webdriver.chrome.service import Service
import time
s = Service("C:/Users/DARSHAN/Desktop/Placement-webapp-using-Django-master/chromedriver_win32 (1)/chromedriver.exe")
driver = webdriver.Chrome(service=s)
driver.get(" http://127.0.0.1:8000/")
time.sleep(2)
print(driver.title)
driver.get("http://127.0.0.1:8000/register/")
time.sleep(2)
print(driver.title)
driver.get("http://127.0.0.1:8000/login/")
time.sleep(2)
print(driver.title)
driver.back()
time.sleep(5)
print(driver.title)
driver.forward()
time.sleep(2)
print(driver.title)
driver.back()
time.sleep(2)
print(driver.title)
driver.back()
time.sleep(2)
print(driver.title)
print("Test Successfull")
driver.quit()
